[package]
name = "papers-tools"
version = "0.1.0"
edition = "2021"
authors = ["creepycode"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
haxeformat = "0.2.3"
serde = { version = "1.0.197", features = ["derive"] }
clap = "4.5.4"
clap_derive = "4.5.4"
walkdir = "2.5.0"
thiserror = "1.0.58"
anyhow = "1.0.81"
tempfile = "3.10.1"
zip = "0.6.6"
byteorder = "1.5.0"
binrw = "0.13.3"