name: PSP Papers Tools

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable-x86_64-pc-windows-gnu
          rustup target add x86_64-pc-windows-gnu

      - name: Install Cargo dependencies
        run: cargo update

      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PspPapersModInstaller
          path: ./target/x86_64-pc-windows-gnu/release/papers-tools.exe