name: PSP Papers Tools

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "x86_64-pc-windows-gnu"

      - name: Install Cargo dependencies
        run: cargo update

      - name: Build
        run: |
          rustup target add x86_64-pc-windows-gnu
          cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PspPapersModInstaller
          path: ./target/x86_64-pc-windows-gnu/release/papers-tools.exe